{
 "title": "Ecowitt",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Solar Radiation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "W/m2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_station\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ecowitt\")\n  |> filter(fn: (r) => r[\"_field\"] == \"solarradiation\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_station\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ecowitt\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\" or r[\"_field\"] == \"humidityin\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_station\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ecowitt\")\n  |> filter(fn: (r) => r[\"_field\"] == \"baromrelin\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_station\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ecowitt\")\n  |> filter(fn: (r) => r[\"_field\"] == \"uv\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_station\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ecowitt\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tempinf\" or r[\"_field\"] == \"tempf\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Rain rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthin" } },
   "targets": [
    {
     "query": "from(bucket: \"weather_station\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ecowitt\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rainratein\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\nfrom(bucket: \"weather_station\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ecowitt\")\n  |> filter(fn: (r) => strings.containsStr(v: r._field, substr: \"batt\"))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"weather_station\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ecowitt\")\n  |> filter(fn: (r) => r[\"_field\"] == \"winddir\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Wind",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_station\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ecowitt\")\n  |> filter(fn: (r) => r[\"_field\"] == \"windgustmph\" or r[\"_field\"] == \"windspeedmph\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}